### ISSUE TITLE
通过命令行调用如果有注释就会报错

### ISSUE THREAD

**Issue by yaochiqkl** [leeluolee/mcss#12]
` you have a mcss.json in pwd, but has Error: Unexpected token /`\
解决方式竟然是删掉注释就好

**Comment by yaochiqkl** [comment]
Windows平台

**Comment by leeluolee** [comment]
json不允许注释噢。。

**Comment by yaochiqkl** [comment]
.....原来是这样  不好意思啦 :laughing:
